Local development URLs loaded
System check identified no issues (0 silenced).
August 04, 2025 - 06:38:13
Django version 5.2.2, using settings 'jobsp.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Invalid HTTP_HOST header: 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev'. You may need to add 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev'. You may need to add 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev' to ALLOWED_HOSTS.
[2025-08-04 06:38:14,445] WARNING [django.request:253] Bad Request: /
Bad Request: /
[04/Aug/2025 06:38:14] "GET / HTTP/1.1" 400 127311
Invalid HTTP_HOST header: 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev'. You may need to add 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/django/http/request.py", line 191, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev'. You may need to add 'e21e59bf-2612-4616-992a-3aa3f890fa0b-00-bb4hxs9kmtuc.sisko.replit.dev' to ALLOWED_HOSTS.
[2025-08-04 06:38:14,512] WARNING [django.request:253] Bad Request: /
Bad Request: /
[04/Aug/2025 06:38:14] "GET / HTTP/1.1" 400 127310
